/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Song = IDL.Record({
  'id' : IDL.Text,
  'bpm' : IDL.Nat,
  'key' : IDL.Text,
  'title' : IDL.Text,
  'album' : IDL.Text,
  'description' : IDL.Text,
  'genre' : IDL.Text,
  'thumbUrl' : IDL.Text,
  'artist' : IDL.Text,
});
export const Chord = IDL.Record({
  'romanNumeral' : IDL.Text,
  'chordType' : IDL.Text,
  'name' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'addFavorite' : IDL.Func([Song], [], []),
  'generateChordProgression' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Chord)],
      [],
    ),
  'getArtistDetails' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getFavorites' : IDL.Func([], [IDL.Vec(Song)], ['query']),
  'removeFavorite' : IDL.Func([IDL.Text], [], []),
  'searchSongs' : IDL.Func([IDL.Text], [IDL.Text], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Song = IDL.Record({
    'id' : IDL.Text,
    'bpm' : IDL.Nat,
    'key' : IDL.Text,
    'title' : IDL.Text,
    'album' : IDL.Text,
    'description' : IDL.Text,
    'genre' : IDL.Text,
    'thumbUrl' : IDL.Text,
    'artist' : IDL.Text,
  });
  const Chord = IDL.Record({
    'romanNumeral' : IDL.Text,
    'chordType' : IDL.Text,
    'name' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'addFavorite' : IDL.Func([Song], [], []),
    'generateChordProgression' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Chord)],
        [],
      ),
    'getArtistDetails' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getFavorites' : IDL.Func([], [IDL.Vec(Song)], ['query']),
    'removeFavorite' : IDL.Func([IDL.Text], [], []),
    'searchSongs' : IDL.Func([IDL.Text], [IDL.Text], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };